### ISSUE TITLE
pretrain models and visualization code

### ISSUE THREAD

**Issue by WilsonWangTHU** [boreshkinai/delta-interpolator#1]
Hi!

Great work!

I wonder if there's a pretrained model we can play with and whether it's possible to release a visualization code?
also there's a type in `docker exec -i -t pose_estimation_$USER  /bin/bash`. it should be `delta_interpolator_$USER` i think?
thanks in advance
best regards

**Comment by boreshkinai** [comment]
Added pretrained model
