### ISSUE TITLE
Pretrained model is not accessible.

### ISSUE THREAD

**Issue by ghost** [boreshkinai/delta-interpolator#6]
Such error occurs when clicking [https://storage.googleapis.com/delta-interpolator/pretrained_model.zip](https://storage.googleapis.com/delta-interpolator/pretrained_model.zip), would you mind updating the url ?
<img width="561" alt="Snipaste_2022-08-15_10-57-17" src="https://user-images.githubusercontent.com/30871295/184569774-c8b33138-023a-4ded-9d04-f39034c176ce.png">

**Comment by boreshkinai** [comment]
Resolved, thanks for flagging!

**Comment by boreshkinai** [comment]
resolved
